version: 2
jobs:
  build:
    docker:
      - image: openjdk:12-alpine
    steps:
      - checkout
      - run: ./gradlew build
      - persist_to_workspace:
          root: .
          paths:
            - ./build/libs/

workflows:
  version: 2
  workflow:
    jobs:
    - build