version: 2

jobs:
  build:
    docker:
      - image: circleci/openjdk:12-alpine
    steps:
      - checkout
      - run: ./gradlew build
      - persist_to_workspace:
          root: .
          paths:
            - ./build/libs/

Cars_CI_CD:
    workflows:
      jobs:
        - build