version: 2
jobs:
  build:
    docker:
      - image: openjdk:12-alpine
    steps:
      - checkout
      - run: ./gradlew build
      - persist_to_workspace:
          root: .
          paths:
            - ./build/libs/
  smoke test:
    docker:
      - image: openjdk:12-alpine
    steps:
      - checkout
      - run:
        name: check the build
        command: |
          apk --no-cache add curl
          java -jar ./build/libs/cars-api.jar &
          sleep 30
          curl http://localhost:5000/actuator/health | grep "UP"


workflows:
  version: 2
  workflow:
    jobs:
    - build
    - smoke test:
        requires: [build]